### PR TITLE
Added basic signup constraints.

### PR DESCRIPTION
**Pull request by zsmoore**
Addresses #73 

Added most basic signup constraints.

Chained the ors in order to modify code as minimal as possible.
If there are any style changes that the project prefers let me know.

### CODE REVIEW

**Comment by zsmoore** [comment]
@benreid24.

That case is already handled if you test out the code. You don't need to regex because there is the lastIndexOf method.

Test out an email that you are thinking and it will go through.

**Comment by zsmoore** [comment]
@jacobfij 
Thanks! I also enforce that if there is a period there is atleast one character after it in the email.

**Comment by benreid24** [comment]
This will still allow invalid emails. It does nothing to valid the characters in each part of the email, nor ensure that '@' appears only once. Below is the "official" regex to validate an email based on the RFC 5322 standard. Do we need this? Probably not, but regex is easy to use and we won't have any weird outlier cases to worry about

\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*
 |  "(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]
      |  \\[\x01-\x09\x0b\x0c\x0e-\x7f])*")
@ (?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?
  |  \[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}
       (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:
          (?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]
          |  \\[\x01-\x09\x0b\x0c\x0e-\x7f])+)
     \])\z

**Comment by jacobfij** [comment]
@benreid24 True. i wasn't going to be super strict about the constraints but i suppose we may as handle that as well while we're at it.

**Comment by benreid24** [comment]
Gonna be fully honest I'm being a pain because I'm jealous. My assigned task is scripting an entire game AI and you got 3 if statements. If you really don't want to add the regex I'll just merge it, this is good enough

**Comment by rachelaroberts** [comment]
@zsmoore i am very happy with your contribution lol you completed everything i specified in my description, so you’ve completed this perfectly as far as i’m concerned.

**Comment by zsmoore** [comment]
@benreid24 
I'll add the regex in an hour or so then ping you once it is in.  Not being a pain I understand that the sign up should be safer.

**Comment by zsmoore** [comment]
@benreid24 
Regex has been swapped in.  Test it out and let me know if there are any issues.

The regex provided in your comment didn't actually work so I searched for a new one which seems to work well.  Feel free to try out some edge cases though.

**Pull request merged**
