### PR TITLE
Forgot password button

### PR DESCRIPTION
**Pull request by Nbot07**
#74

### CODE REVIEW

**Comment by benreid24** [comment]
Obviously we don't want this

**Comment by jacobfij** [comment]
I'm assuming it wasn't expected that you'd be doing your actual work on this PR, since we had to have some trivial change for class. As you are, I'll reopen.  You've technically completed the task, so if you're feeling particularly lazy / aren't at all familiar with node.js and don't care to learn, you can call it a day.   However, in order to actually use this button, we'll need to use redux to connect it to the backend to actually send an email or something.  If you're feeling ambitious, you could set that process up for us with the following: 

1.) create a function in src/actions/homepage.js which would ultimately trigger a popup that informs them they've been emailed, but for now could just close the popup (hint: return { type: SET_POPUP, payload: { currentPopup: '' } }; *cough cough*).

2.) add the action to mapDispatchToProps() in src/components/Homepage.js

3.) propogate to the login page (use the login function as a guide)

4.) instead of just printing on button click, call that function.

In the 'bonus' of the issue description, this was essentially what I had in mind.  However, I since remembered that not doing anything in the action will cause an error, so I've adjusted tthat slighlty here.

**Comment by rachelaroberts** [comment]
@Nbot07 it looks like in you labeled the button "Password" instead of "Forgot Password"

**Comment by Nbot07** [comment]
@rachelaroberts updated "Password" to "Forgot Password"

**Comment by jacobfij** [comment]
Closing the pull request, as we don't want to add a non-usable button at this point.  If we end up implimenting the 'forgot password', this can be re-opened.

**Pull request closed without merging**
